name: nzlusdb
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - h5netcdf >=1.6.0
  - lsapy >=0.2.0
  - matplotlib >=3.9.0
  - xclim >=0.55.1
  # extra
  # dev
  - bump-my-version >=1.2.0
  - codespell >=2.4.1
  - pre-commit >=4.4.0
  - ruff >=0.12.0
