project:
  type: website
  output-dir: _build

# tell quarto to read the generated styles
format:
  html:
    toc: true
    theme: cosmo

website:
  title: NZ Land Use Suitability Database
  page-navigation: true
  navbar:
    # search: false
    title: nzlusdb
    left:
      - text: Home
        href: index.md
      - text: Method
        href: method.md
      - text: Land Uses
        menu:
          - text: Land Use
            href: landuses/landuse.md
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/baptistehamon/nzlusdb
  page-footer:
    left: |
      NZ Land Use Suitability Database<br>Â© 2025, <a href="https://www.linkedin.com/in/baptiste-hamon-75378114b" target="_blank">Baptiste Hamon</a>
    right: |
      [![](/_static/logos/FT2050-full_colour.png){fig-alt="Food Transition 2050" height=75px}](https://www.canterbury.ac.nz)
      [![](/_static/logos/UCBlack.png){fig-alt="University of Canterbury" height=75px}](https://www.canterbury.ac.nz)
